face-analyzer/src/views/projects/AddExperimentModal.js

- hard core projectId for MVP
- refresh page after submitting
- handle change for experiment description

Fix Add experiment bugs

---

face-analyzer/src/routes/MainRoutes.js
face-analyzer/src/views/experiment/AddStimuliModal.js
face-analyzer/src/views/experiment/StimuliCard.js
face-analyzer/src/views/stimuli/StimuliHeader.js
face-analyzer/src/views/stimuli/charts/BoxPlotChart.js
face-analyzer/src/views/stimuli/charts/ChartHeader.js
face-analyzer/src/views/stimuli/charts/dummy-chart-data.js
face-analyzer/src/views/stimuli/charts/index.js

- time graph 
- box plot
- added name to stimuli cards and form

24 user sees emotions over time graph & 25 box plot

---

face-analyzer/src/views/reactions/AnalysisDataFunctions.js

Sends one API call to both send emotion data in an array and create a new reaction, instead of first creating the reaction and then sending the emotions one by one, thus saving network resources.

Optimized PUT for reactions and emotions

---

face-analyzer/package.json
face-analyzer/src/routes/MainRoutes.js
face-analyzer/src/views/experiment/ExperimentHeader.js
face-analyzer/src/views/projects/BackendEndpoints.js
face-analyzer/src/views/reactions/AnalysisResultsComponent.js
face-analyzer/src/views/reactions/WebcamCanvas.js
face-analyzer/src/views/reactions/WebcamSetup.js
face-analyzer/src/views/stimuli/ReactionsContent.js
face-analyzer/src/views/stimuli/StimuliHeader.js
face-analyzer/src/views/stimuli/charts/BoxPlotChart.js
face-analyzer/src/views/stimuli/charts/ChartHeader.js
face-analyzer/src/views/stimuli/charts/dummy-chart-data.js
face-analyzer/src/views/stimuli/charts/index.js
face-analyzer/src/views/stimuli/index.js

Added the functionality that shows saved reactions' emotions on either a line graph or a box-plot graph.

Showing emotions on graphs

---

face-analyzer/src/views/stimuli/charts/index.js

Changed code for getting reactions to use the fixed reactions/{id} endpoint

Changed code for getting reactions 

---

face-analyzer/src/views/stimuli/ReactionsContent.js
face-analyzer/src/views/stimuli/charts/index.js

Removed unused imports

---

face-analyzer/src/views/experiments/index.js
face-analyzer/src/views/projects/experiments.js
face-analyzer/src/views/stimuli/charts/ChartHeader.js
face-analyzer/src/views/stimuli/charts/index.js

Added links to project, experiment and stimulus for easier access (no env variables this time hihi)

update header in in statistics (without env variables this time :))

---

face-analyzer/src/context/authContext.js
face-analyzer/src/layout/MainLayout/Sidebar/MenuList/index.js
face-analyzer/src/ui-component/modals/users/AddUserModal.js

Fixed add user, fixed warnings, fixed proptypes

Fixed add user, warnings, proptypes

---

face-analyzer/src/ui-component/modals/stimuli/DeleteReactionModal.js
face-analyzer/src/ui-component/modals/stimuli/SaveReactionModal.js
face-analyzer/src/views/reactions/AnalysisDataFunctions.js
face-analyzer/src/views/stimuli/ReactionsContent.js
face-analyzer/src/views/stimuli/index.js

Added a modal for adding participant name and fixed reaction deletion

Added a modal for adding participant name

---

face-analyzer/src/ui-component/modals/stimuli/DeleteReactionModal.js
face-analyzer/src/ui-component/modals/stimuli/SaveReactionModal.js
face-analyzer/src/views/stimuli/charts/BoxPlotChart.js
face-analyzer/src/views/stimuli/charts/BoxPlotLegend.js
face-analyzer/src/views/stimuli/charts/index.js

Added a box plot legend, fixed several prop-type warnings and added a little QoL "Reaction Duration" value on the box plot/emotion distribution page.
<b> Not sure if the links for box plots are a good option, please give me your feedback! </b>

Added a box plot legend

---

face-analyzer/src/endpoints/BackendEndpoints.js
face-analyzer/src/ui-component/modals/users/EditUserModal.js
face-analyzer/src/views/users/UserDataGrid.js
face-analyzer/src/views/users/user_management.js

Implemented the functionality to edit users as an admin. An admin can edit any user and optionally change the password during that same process.

Editing user data

---

face-analyzer/src/ui-component/cards/experiments/notes/NoteCard.js

I messed up the notes. Now they should not be messed up any more.

Fixing note card

---

face-analyzer/src/ui-component/cards/experiments/StimuliCard.js
face-analyzer/src/ui-component/cards/projects/ExperimentCard.js
face-analyzer/src/ui-component/cards/projects/ProjectCard.js
face-analyzer/src/ui-component/headers/ChartHeader.js
face-analyzer/src/ui-component/headers/ExperimentHeader.js
face-analyzer/src/ui-component/headers/NotesHeader.js
face-analyzer/src/ui-component/headers/ProjectHeader.js
face-analyzer/src/ui-component/headers/ResearcherHeader.js
face-analyzer/src/ui-component/headers/StimuliHeader.js
face-analyzer/src/ui-component/modals/experiments/AddStimuliModal.js
face-analyzer/src/ui-component/modals/experiments/DeleteStimuliModal.js
face-analyzer/src/ui-component/modals/experiments/notes/AddNoteModal.js
face-analyzer/src/ui-component/modals/experiments/notes/DeleteNoteModal.js
face-analyzer/src/ui-component/modals/experiments/notes/EditNoteModal.js
face-analyzer/src/ui-component/modals/projects/AddExperimentModal.js
face-analyzer/src/ui-component/modals/projects/AddProjectModal.js
face-analyzer/src/ui-component/modals/projects/DeleteExperimentModal.js
face-analyzer/src/ui-component/modals/projects/DeleteProjectModal.js
face-analyzer/src/ui-component/modals/projects/EditExperimentModal.js
face-analyzer/src/ui-component/modals/projects/EditProjectModal.js
face-analyzer/src/ui-component/modals/projects/researchers/AddUserToProjectModal.js
face-analyzer/src/ui-component/modals/projects/researchers/RemoveUserFromProjectModal.js
face-analyzer/src/ui-component/modals/stimuli/DeleteReactionModal.js
face-analyzer/src/ui-component/modals/stimuli/SaveReactionModal.js
face-analyzer/src/ui-component/modals/users/AddUserModal.js
face-analyzer/src/ui-component/modals/users/DeleteUserModal.js
face-analyzer/src/ui-component/modals/users/EditUserModal.js
face-analyzer/src/views/reactions/WebcamSetup.js
face-analyzer/src/views/stimuli/ReactionsContent.js
face-analyzer/src/views/stimuli/index.js

Trying to use useNavigate wherever possible.

Making navigation consistent across all components, fixing webcam

---

face-analyzer/package.json
face-analyzer/src/ui-component/headers/ChartHeader.js
face-analyzer/src/views/reactions/VisageProcessing.js
face-analyzer/src/views/stimuli/charts/DynamicChart.js
face-analyzer/src/views/stimuli/charts/EmotionsOverTimeChart.js
face-analyzer/src/views/stimuli/charts/NewChart.js
face-analyzer/src/views/stimuli/charts/index.js
face-analyzer/src/views/stimuli/index.js

I can get current timestamp of the video, but the chart API doesn't really support this

Dynamic charts

---

.github/workflows/deploy-staging.yml

Staging cluster is not deployed.

Temporarily disable staging

---

face-analyzer/src/views/pages/authentication/auth-forms/AuthLogin.js
face-analyzer/src/views/stimuli/index.js

Fixing various problems related to video playback

---

face-analyzer/package.json
face-analyzer/src/endpoints/BackendEndpoints.js
face-analyzer/src/routes/MainRoutes.js
face-analyzer/src/ui-component/headers/ChartHeader.js
face-analyzer/src/ui-component/headers/CollectiveChartHeader.js
face-analyzer/src/ui-component/headers/ExperimentHeader.js
face-analyzer/src/views/stimuli/ReactionsContent.js
face-analyzer/src/views/stimuli/charts/index.js
face-analyzer/src/views/stimuli/collective/CollectiveChart.js
face-analyzer/src/views/stimuli/collective/CollectiveStatistics.js

Created a new page for the collective statistics. It shows a chart with a line and an area around it. The line represents average data accross all recorded reactions, and the area represents one standard deviation from that average. Still need to add the appropriate headers and similar housekeeping stuff, but the meaty part is considreded finished.

Collective statistics

---

face-analyzer/src/routes/MainRoutes.js
face-analyzer/src/views/stimuli/charts/DynamicChart.js
face-analyzer/src/views/stimuli/charts/NewChart.js

The user can now click on a specific timestamp on the chart and the video will seek to that timestamp.

Choose timestamp from chart

---

face-analyzer/src/routes/MainRoutes.js
face-analyzer/src/views/stimuli/collective/CollectiveChart.js

Changed the Area fill opacity from 0.3 to 0.2

Changed Area opacity

---

face-analyzer/src/layout/MainLayout/Sidebar/MenuList/NavCollapse/index.js
face-analyzer/src/ui-component/cards/GenericAddCard.js
face-analyzer/src/ui-component/cards/experiments/StimuliCard.js
face-analyzer/src/ui-component/cards/experiments/notes/NoteCard.js
face-analyzer/src/ui-component/cards/projects/AddExperimentCard.js
face-analyzer/src/ui-component/headers/CollectiveChartHeader.js
face-analyzer/src/ui-component/modals/users/EditUserModal.js
face-analyzer/src/views/error-page/ErrorPage.js
face-analyzer/src/views/projects/projects.js
face-analyzer/src/views/reactions/WebcamSetup.js
face-analyzer/src/views/stimuli/charts/BoxPlotChart.js
face-analyzer/src/views/stimuli/charts/DynamicChart.js
face-analyzer/src/views/stimuli/charts/EmotionsOverTimeChart.js
face-analyzer/src/views/stimuli/charts/NewChart.js
face-analyzer/src/views/stimuli/collective/CollectiveChart.js
face-analyzer/src/views/stimuli/index.js

Already merged with the test-ci branch

Fixed proptypes and misc
